### ISSUE TITLE
Loading hdf5 with the correct signal shape

### ISSUE THREAD

**Issue by thomasaarholt** [niermann/temscript#1]
Currently when I try to load my EELS spectrum image saved as a hdf5 from hyperspy (Image with a spectrum in each pixel), DM doesn't know how to format the signal. It attempts to form an image with the spectrum channels on the x axis and the image y-axis as the yaxis. I can solve it by using the Gatan Volume package to rotate about the y-axis, but it isn't exactly ideal. It would be nice if the reader could look the shape information saved in the metadata and implement it correctly in loaded signal.

**Comment by niermann** [comment]
Just noticed this issue... this probably relates to the project gms_plugin_hdf5 and was already discussed there last summer. So I'm closing it here.

**Comment by thomasaarholt** [comment]
Huh, I'm unsure why I posted it here then. Cheers though.
