### ISSUE TITLE
Testing STEM acquistion

### ISSUE THREAD

**Issue by thomasaarholt** [niermann/temscript#3]
Hi Tore! I'm keen to try doing some STEM acquisitions with this library (specifically, acquiring an image series as a function of scan rotation). Before starting I thought I'd just ask here to see if there was anything I should be aware of - I saw that the STEM aspects were untested, but I'm happy to contribute with a PR if necessary.

**Comment by thomasaarholt** [comment]
It seems to be working pretty nicely! Here is an example script that might be useful for someone else:

https://gist.github.com/thomasaarholt/6e3b2d14e20c0c1c3ba88cab886655b0

**Comment by niermann** [comment]
Hi Thomas. Great to hear it is working, even though the STEM acquisition was never tested. Temscript uses the FEI scripting adapter so it is limited to whatever is possible with the scripting adapter (and temscript also inherits its bugs....). With this respect I can give only the advice to read the scripting adapter's manual. According to the manual there are some caveats, regarding what STEM detectors can be used (they have to be selected in the TEM UI, as far as I remember).

**Comment by niermann** [comment]
This seems settled...
