### ISSUE TITLE
STEM image pixel shape

### ISSUE THREAD

**Issue by thomasaarholt** [niermann/temscript#5]
Currently the pixel size for a STEM acquisition is set in the same way one would for a fixed-pixel-size CCD: Using "FULL", "HALF" etc.
It would be nice to specify it using a pixel size i.e. 512x512.

**Comment by thomasaarholt** [comment]
Since you probably haven't tested it - currently this is the behaviour:

With "Full", it acquires a STEM image across what would be the "full" area that would normally be scanned by the microscope software. With "Half" or "Quarter", it reduces the area that is scanned, effectively magnifying the image. The pixel shape also reduces (from 2kx2k to 1kx1k to 512x512).

**Comment by thomasaarholt** [comment]
The way it normally works in STEM mode is that you adjust magnification to set the field of view, and then acquire that region with a number of pixels (512 x 512, 1k x 1k, etc).

**Comment by niermann** [comment]
To my knowledge, there is no corresponding function in FEI's scripting adapter, which could be used by the temscript module to achieve this.
