### ISSUE TITLE
STEM Pixel Calibration

### ISSUE THREAD

**Issue by thomasaarholt** [niermann/temscript#6]
There is no way to calibrate the physical size of the image (um/nm) in STEM mode at the moment. There is probably either a pixel size or field of view size one could get?

**Comment by niermann** [comment]
To my knowledge there is no function in the FEI TEM scripting API to retrieve this information. This is indeed a very essential metadata, which cannot be retrieved from the FEI adapter. You can partially use the magnification index and projection mode to create your own lookup table. 

For our microscope (Titan V1.1) also you also can't read the actual magnification in imaging modes, just its magnification index. That seems to be a bug in FEI's adapter.
